/**
 * Tests for the kb engine's classification, ordering, pinned flag, and
 * directory management over an in-memory fs fake. The wire Remote layer is
 * generated by Typert; these tests pin the engine behavior beneath it.
 */

import { beforeEach, describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import { KbEngine, statusOf, DEFAULT_ARCHIVE_DIR } from '../src/core.ts'
import { MemoryFs } from './memory-fs.ts'

/** One seeded markdown document with frontmatter. */
function doc(title: string, updated: string, extra = ''): string {
  return `---\ntitle: ${title}\nupdated: ${updated}\n${extra}---\n\n正文 ${title}\n`
}

describe('statusOf', () => {
  it('derives inbox from either inbox root and archived from the archive directory', () => {
    expect(statusOf('00-inbox/a.md')).toBe('inbox')
    expect(statusOf('01-inbox/b.md')).toBe('inbox')
    expect(statusOf('10-技术/c.md')).toBe('filed')
    expect(statusOf('c.md')).toBe('filed')
    expect(statusOf('90-归档/d.md')).toBe('archived')
  })

  it('honors a configured archive directory', () => {
    expect(statusOf('99-存档/a.md', '99-存档')).toBe('archived')
    expect(statusOf('90-归档/a.md', '99-存档')).toBe('filed')
  })
})

describe('KbEngine list and pinned', () => {
  let fs: MemoryFs
  let engine: KbEngine

  beforeEach(async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    fs = ctx.fs as MemoryFs
    fs.seed('kb/00-inbox/2026-08-10-a.md', doc('甲', '2026-08-10'))
    fs.seed('kb/10-技术/2026-08-12-b.md', doc('乙', '2026-08-12'))
    fs.seed('kb/10-技术/2026-08-13-c.md', doc('丙', '2026-08-13'))
    engine = new KbEngine(fs, undefined)
    await engine.ensureInit()
  })

  it('orders pinned first, then most recently updated', async () => {
    await engine.save({ path: '00-inbox/2026-08-10-a.md', pinned: true })
    const docs = await engine.list({})
    expect(docs.map(doc => doc.title)).toEqual(['甲', '丙', '乙'])
    expect(docs[0]?.pinned).toBe(true)
    expect(docs[1]?.pinned).toBe(false)
  })

  it('writes and removes the pinned frontmatter flag', async () => {
    await engine.save({ path: '10-技术/2026-08-13-c.md', pinned: true })
    let result = await engine.get({ path: '10-技术/2026-08-13-c.md' })
    expect(result.meta.pinned).toBe('true')
    await engine.save({ path: '10-技术/2026-08-13-c.md', pinned: false })
    result = await engine.get({ path: '10-技术/2026-08-13-c.md' })
    expect(result.meta.pinned).toBeUndefined()
    expect((await engine.list({})).every(doc => !doc.pinned)).toBe(true)
  })

  it('supports a pinned flag at creation', async () => {
    const created = await engine.create({ title: '丁', directory: '20-学习笔记', pinned: true })
    const docs = await engine.list({})
    expect(docs[0]).toMatchObject({ path: created.path, title: '丁', pinned: true })
  })

  it('reports the configured archive directory through stats and dirs', async () => {
    const custom = new KbEngine(fs, undefined, '99-存档')
    await custom.ensureInit()
    const stats = await custom.stats()
    expect(stats.byStatus.archived).toBe(0)
    expect(stats.archiveDir).toBe('99-存档')
    const dirs = await custom.dirs()
    expect(dirs).toContain('99-存档')
    expect(dirs).not.toContain(DEFAULT_ARCHIVE_DIR)
  })
})

describe('KbEngine directory management', () => {
  let fs: MemoryFs
  let engine: KbEngine

  beforeEach(async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/2026-08-12-a.md', doc('甲', '2026-08-12'))
    fs.seed('kb/10-技术/11-AI/2026-08-13-b.md', doc('乙', '2026-08-13'))
    engine = new KbEngine(fs, undefined)
    await engine.ensureInit()
  })

  it('creates a nested directory through a .keep marker', async () => {
    const result = await engine.createDir({ directory: '10-技术/12-前端' })
    expect(result).toEqual({ directory: '10-技术/12-前端' })
    expect(fs.entries.has('kb/10-技术/12-前端/.keep')).toBe(true)
  })

  it('refuses invalid, reserved, and existing directories', async () => {
    await expect(engine.createDir({ directory: '' })).rejects.toThrow(/目录名无效/)
    await expect(engine.createDir({ directory: '00-inbox/x' })).rejects.toThrow(/保留目录不可新建/)
    await expect(engine.createDir({ directory: '_meta/x' })).rejects.toThrow(/保留目录不可新建/)
    await engine.createDir({ directory: '10-技术/12-前端' })
    await expect(engine.createDir({ directory: '10-技术/12-前端' })).rejects.toThrow(/目录已存在/)
    await expect(engine.createDir({ directory: '10-技术/11-AI' })).rejects.toThrow(/目录已存在/)
  })

  it('renames a directory, relocating documents and nested directories', async () => {
    const result = await engine.renameDir({ directory: '10-技术', name: '11-技术' })
    expect(result).toEqual({ from: '10-技术', to: '11-技术', moved: 2 })
    expect(fs.entries.get('kb/10-技术/2026-08-12-a.md')?.text).toBe(' ')
    const docs = await engine.list({})
    expect(docs.map(doc => doc.path).sort()).toEqual([
      '11-技术/11-AI/2026-08-13-b.md',
      '11-技术/2026-08-12-a.md',
    ])
  })

  it('drops a moved or removed document from the index', async () => {
    await engine.move({ path: '10-技术/2026-08-12-a.md', targetDirectory: '20-学习笔记' })
    let paths = (await engine.list({})).map(doc => doc.path)
    expect(paths).not.toContain('10-技术/2026-08-12-a.md')
    expect(paths).toContain('20-学习笔记/2026-08-12-a.md')
    await engine.remove({ path: '20-学习笔记/2026-08-12-a.md' })
    paths = (await engine.list({})).map(doc => doc.path)
    expect(paths).not.toContain('20-学习笔记/2026-08-12-a.md')
  })

  it('purge removes a trashed document from the trash listing', async () => {
    await engine.remove({ path: '10-技术/2026-08-12-a.md' })
    const entries = await engine.trash()
    expect(entries.docs).toHaveLength(1)
    await engine.purge({ path: entries.docs[0]!.path })
    expect((await engine.trash()).docs).toHaveLength(0)
  })

  it('refuses to rename reserved roots, the archive directory, or onto an existing path', async () => {
    await expect(engine.renameDir({ directory: '00-inbox', name: 'x' })).rejects.toThrow(/保留目录不可重命名/)
    await expect(engine.renameDir({ directory: DEFAULT_ARCHIVE_DIR, name: 'x' })).rejects.toThrow(/保留目录不可重命名/)
    await expect(engine.renameDir({ directory: '10-技术', name: 'a/b' })).rejects.toThrow(/目录名无效/)
    await expect(engine.renameDir({ directory: '不存在', name: 'x' })).rejects.toThrow(/目录不存在/)
    fs.seed('kb/20-学习笔记/.keep', '')
    await expect(engine.renameDir({ directory: '10-技术', name: '20-学习笔记' })).rejects.toThrow(/目标目录已存在/)
  })
})

describe('KbEngine image fallback', () => {
  it('resolves a moved document image through the registry by basename', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/11-AI/diagram.png', 'png-bytes')
    fs.seed('kb/_meta/images.json', JSON.stringify({
      schemaVersion: 1,
      images: { '10-技术/11-AI/diagram.png': {} },
    }))
    const engine = new KbEngine(fs, undefined)
    // The document's new directory does not carry the image; the registry does.
    const result = await engine.image('00-inbox/diagram.png')
    expect(new TextDecoder().decode(result.bytes)).toBe('png-bytes')
    expect(result.mime).toBe('image/png')
  })

  it('still fails an unknown image', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const engine = new KbEngine(ctx.fs, undefined)
    await expect(engine.image('00-inbox/missing.png')).rejects.toThrow(/图片不存在/)
  })
})

describe('KbEngine purge image cascade', () => {
  /** Seed one library with a document and an image, and index it. */
  async function bench(body: string, otherBody?: string): Promise<{ fs: MemoryFs; engine: KbEngine }> {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/11-AI/2026-08-14-a.md', doc('甲', '2026-08-14', '') + body)
    if (otherBody !== undefined) {
      fs.seed('kb/10-技术/2026-08-14-b.md', doc('乙', '2026-08-14', '') + otherBody)
    }
    fs.seed('kb/10-技术/11-AI/diagram.png', 'png-bytes')
    fs.seed('kb/_meta/images.json', JSON.stringify({
      schemaVersion: 1,
      images: { '10-技术/11-AI/diagram.png': {} },
    }))
    const engine = new KbEngine(fs, undefined)
    await engine.ensureInit()
    return { fs, engine }
  }

  it('blanks and unregisters an exclusively referenced image on purge', async () => {
    const { fs, engine } = await bench('正文 ![[diagram.png]]')
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const entries = await engine.trash()
    await engine.purge({ path: entries.docs[0]!.path })
    expect(fs.entries.get('kb/10-技术/11-AI/diagram.png')?.text.trim()).toBe('')
    await expect(engine.image('10-技术/11-AI/diagram.png')).rejects.toThrow(/图片不存在/)
  })

  it('keeps an image another document still references', async () => {
    const { engine } = await bench('正文 ![[diagram.png]]', '另一篇 ![[11-AI/diagram.png]]')
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const entries = await engine.trash()
    await engine.purge({ path: entries.docs[0]!.path })
    const result = await engine.image('10-技术/11-AI/diagram.png')
    expect(new TextDecoder().decode(result.bytes)).toBe('png-bytes')
  })
})
