/**
 * Tests for the kb engine's classification, ordering, pinned flag, and
 * directory management over an in-memory fs fake. The wire Remote layer is
 * generated by Typert; these tests pin the engine behavior beneath it.
 */

import { beforeEach, describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import { KbEngine, statusOf, DEFAULT_ARCHIVE_DIR } from '../src/core.ts'
import { MemoryFs } from './memory-fs.ts'

/** One seeded markdown document with frontmatter. */
function doc(title: string, updated: string, extra = ''): string {
  return `---\ntitle: ${title}\nupdated: ${updated}\n${extra}---\n\n正文 ${title}\n`
}

describe('statusOf', () => {
  it('derives inbox from either inbox root and archived from the archive directory', () => {
    expect(statusOf('00-inbox/a.md')).toBe('inbox')
    expect(statusOf('01-inbox/b.md')).toBe('inbox')
    expect(statusOf('10-技术/c.md')).toBe('filed')
    expect(statusOf('c.md')).toBe('filed')
    expect(statusOf('90-归档/d.md')).toBe('archived')
  })

  it('honors a configured archive directory', () => {
    expect(statusOf('99-存档/a.md', '99-存档')).toBe('archived')
    expect(statusOf('90-归档/a.md', '99-存档')).toBe('filed')
  })
})

describe('KbEngine list and pinned', () => {
  let fs: MemoryFs
  let engine: KbEngine

  beforeEach(async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    fs = ctx.fs as MemoryFs
    fs.seed('kb/00-inbox/2026-08-10-a.md', doc('甲', '2026-08-10'))
    fs.seed('kb/10-技术/2026-08-12-b.md', doc('乙', '2026-08-12'))
    fs.seed('kb/10-技术/2026-08-13-c.md', doc('丙', '2026-08-13'))
    engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
  })

  it('orders pinned first, then most recently updated', async () => {
    await engine.save({ path: '00-inbox/2026-08-10-a.md', pinned: true })
    const docs = await engine.list({})
    expect(docs.map(doc => doc.title)).toEqual(['甲', '丙', '乙'])
    expect(docs[0]?.pinned).toBe(true)
    expect(docs[1]?.pinned).toBe(false)
  })

  it('writes and removes the pinned frontmatter flag', async () => {
    await engine.save({ path: '10-技术/2026-08-13-c.md', pinned: true })
    let result = await engine.get({ path: '10-技术/2026-08-13-c.md' })
    expect(result.meta.pinned).toBe('true')
    await engine.save({ path: '10-技术/2026-08-13-c.md', pinned: false })
    result = await engine.get({ path: '10-技术/2026-08-13-c.md' })
    expect(result.meta.pinned).toBeUndefined()
    expect((await engine.list({})).every(doc => !doc.pinned)).toBe(true)
  })

  it('supports a pinned flag at creation', async () => {
    const created = await engine.create({ title: '丁', directory: '20-学习笔记', pinned: true })
    const docs = await engine.list({})
    expect(docs[0]).toMatchObject({ path: created.path, title: '丁', pinned: true })
  })

  it('reports the configured archive directory through stats and dirs', async () => {
    const custom = new KbEngine(fs, 'kb', '99-存档')
    await custom.ensureInit()
    const stats = await custom.stats()
    expect(stats.byStatus.archived).toBe(0)
    expect(stats.archiveDir).toBe('99-存档')
    const dirs = await custom.dirs()
    expect(dirs).toContain('99-存档')
    expect(dirs).not.toContain(DEFAULT_ARCHIVE_DIR)
  })
})

describe('KbEngine directory management', () => {
  let fs: MemoryFs
  let engine: KbEngine

  beforeEach(async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/2026-08-12-a.md', doc('甲', '2026-08-12'))
    fs.seed('kb/10-技术/11-AI/2026-08-13-b.md', doc('乙', '2026-08-13'))
    engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
  })

  it('creates a nested directory through a .keep marker', async () => {
    const result = await engine.createDir({ directory: '10-技术/12-前端' })
    expect(result).toEqual({ directory: '10-技术/12-前端' })
    expect(fs.entries.has('kb/10-技术/12-前端/.keep')).toBe(true)
  })

  it('refuses invalid, reserved, and existing directories', async () => {
    await expect(engine.createDir({ directory: '' })).rejects.toThrow(/目录名无效/)
    await expect(engine.createDir({ directory: '00-inbox/x' })).rejects.toThrow(/保留目录不可新建/)
    await expect(engine.createDir({ directory: '_meta/x' })).rejects.toThrow(/保留目录不可新建/)
    await engine.createDir({ directory: '10-技术/12-前端' })
    await expect(engine.createDir({ directory: '10-技术/12-前端' })).rejects.toThrow(/目录已存在/)
    await expect(engine.createDir({ directory: '10-技术/11-AI' })).rejects.toThrow(/目录已存在/)
  })

  it('renames a directory, relocating documents and nested directories', async () => {
    const result = await engine.renameDir({ directory: '10-技术', name: '11-技术' })
    expect(result).toEqual({ from: '10-技术', to: '11-技术', moved: 2 })
    expect(fs.entries.get('kb/10-技术/2026-08-12-a.md')?.text).toBe(' ')
    const docs = await engine.list({})
    expect(docs.map(doc => doc.path).sort()).toEqual([
      '11-技术/11-AI/2026-08-13-b.md',
      '11-技术/2026-08-12-a.md',
    ])
  })

  it('drops a moved or removed document from the index', async () => {
    await engine.move({ path: '10-技术/2026-08-12-a.md', targetDirectory: '20-学习笔记' })
    let paths = (await engine.list({})).map(doc => doc.path)
    expect(paths).not.toContain('10-技术/2026-08-12-a.md')
    expect(paths).toContain('20-学习笔记/2026-08-12-a.md')
    await engine.remove({ path: '20-学习笔记/2026-08-12-a.md' })
    paths = (await engine.list({})).map(doc => doc.path)
    expect(paths).not.toContain('20-学习笔记/2026-08-12-a.md')
  })

  it('purge removes a trashed document from the trash listing', async () => {
    await engine.remove({ path: '10-技术/2026-08-12-a.md' })
    const entries = await engine.trash()
    expect(entries.docs).toHaveLength(1)
    await engine.purge({ path: entries.docs[0]!.path })
    expect((await engine.trash()).docs).toHaveLength(0)
  })

  it('refuses to rename reserved roots, the archive directory, or onto an existing path', async () => {
    await expect(engine.renameDir({ directory: '00-inbox', name: 'x' })).rejects.toThrow(/保留目录不可重命名/)
    await expect(engine.renameDir({ directory: DEFAULT_ARCHIVE_DIR, name: 'x' })).rejects.toThrow(/保留目录不可重命名/)
    await expect(engine.renameDir({ directory: '10-技术', name: 'a/b' })).rejects.toThrow(/目录名无效/)
    await expect(engine.renameDir({ directory: '不存在', name: 'x' })).rejects.toThrow(/目录不存在/)
    fs.seed('kb/20-学习笔记/.keep', '')
    await expect(engine.renameDir({ directory: '10-技术', name: '20-学习笔记' })).rejects.toThrow(/目标目录已存在/)
  })
})

describe('KbEngine image fallback', () => {
  it('resolves a moved document image through the registry by basename', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/11-AI/diagram.png', 'png-bytes')
    fs.seed('kb/_meta/images.json', JSON.stringify({
      schemaVersion: 1,
      images: { '10-技术/11-AI/diagram.png': {} },
    }))
    const engine = new KbEngine(fs, 'kb')
    // The document's new directory does not carry the image; the registry does.
    const result = await engine.image('00-inbox/diagram.png')
    expect(new TextDecoder().decode(result.bytes)).toBe('png-bytes')
    expect(result.mime).toBe('image/png')
  })

  it('still fails an unknown image', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const engine = new KbEngine(ctx.fs, 'kb')
    await expect(engine.image('00-inbox/missing.png')).rejects.toThrow(/图片不存在/)
  })
})

describe('KbEngine purge image cascade', () => {
  /** Seed one library with a document and an image, and index it. */
  async function bench(body: string, otherBody?: string): Promise<{ fs: MemoryFs; engine: KbEngine }> {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/11-AI/2026-08-14-a.md', doc('甲', '2026-08-14', '') + body)
    if (otherBody !== undefined) {
      fs.seed('kb/10-技术/2026-08-14-b.md', doc('乙', '2026-08-14', '') + otherBody)
    }
    fs.seed('kb/10-技术/11-AI/diagram.png', 'png-bytes')
    fs.seed('kb/_meta/images.json', JSON.stringify({
      schemaVersion: 1,
      images: { '10-技术/11-AI/diagram.png': {} },
    }))
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    return { fs, engine }
  }

  it('blanks and unregisters an exclusively referenced image on purge', async () => {
    const { fs, engine } = await bench('正文 ![[diagram.png]]')
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const entries = await engine.trash()
    await engine.purge({ path: entries.docs[0]!.path })
    expect(fs.entries.get('kb/10-技术/11-AI/diagram.png')?.text.trim()).toBe('')
    await expect(engine.image('10-技术/11-AI/diagram.png')).rejects.toThrow(/图片不存在/)
  })

  it('keeps an image another document still references', async () => {
    const { engine } = await bench('正文 ![[diagram.png]]', '另一篇 ![[11-AI/diagram.png]]')
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const entries = await engine.trash()
    await engine.purge({ path: entries.docs[0]!.path })
    const result = await engine.image('10-技术/11-AI/diagram.png')
    expect(new TextDecoder().decode(result.bytes)).toBe('png-bytes')
  })
})

describe('KbEngine trash retention sweep', () => {
  /** Seed one library with a document, an image, and the image registry. */
  async function bench(body = ''): Promise<{ fs: MemoryFs; engine: KbEngine }> {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/11-AI/2026-08-14-a.md', doc('甲', '2026-08-14', '') + body)
    fs.seed('kb/10-技术/11-AI/diagram.png', 'png-bytes')
    fs.seed('kb/_meta/images.json', JSON.stringify({
      schemaVersion: 1,
      images: { '10-技术/11-AI/diagram.png': {} },
    }))
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    return { fs, engine }
  }

  /** Registry file content as a plain object. */
  function registryOf(fs: MemoryFs): { entries: Record<string, string> } {
    return JSON.parse(fs.entries.get('kb/_meta/trash.json')!.text) as { entries: Record<string, string> }
  }

  /** Backdate the one registry entry to the given age in days. */
  function backdate(fs: MemoryFs, days: number): void {
    const registry = registryOf(fs)
    const path = Object.keys(registry.entries)[0]!
    registry.entries[path] = new Date(Date.now() - days * 86_400_000).toISOString()
    fs.entries.get('kb/_meta/trash.json')!.text = JSON.stringify(registry)
  }

  it('records and reports when a document was deleted', async () => {
    const { engine } = await bench()
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const entries = await engine.trash()
    expect(entries.docs).toHaveLength(1)
    expect(entries.docs[0]?.deletedAt).toBeDefined()
    expect(Date.parse(entries.docs[0]!.deletedAt!)).not.toBeNaN()
  })

  it('sweep purges entries older than the retention window and cascades their images', async () => {
    const { fs, engine } = await bench('正文 ![[diagram.png]]')
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    backdate(fs, 40)
    expect(await engine.sweepTrash(new Date(), 30)).toBe(1)
    expect((await engine.trash()).docs).toHaveLength(0)
    expect(fs.entries.get('kb/10-技术/11-AI/diagram.png')?.text.trim()).toBe('')
  })

  it('sweep keeps entries inside the retention window', async () => {
    const { engine } = await bench()
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    expect(await engine.sweepTrash(new Date(), 30)).toBe(0)
    expect((await engine.trash()).docs).toHaveLength(1)
  })

  it('sweep keeps entries that predate the timestamp registry', async () => {
    const { fs, engine } = await bench()
    fs.seed('kb/.trash/2026-08-01-旧文档.md', doc('旧文档', '2026-08-01'))
    expect(await engine.sweepTrash(new Date(), 1)).toBe(0)
    const entries = await engine.trash()
    expect(entries.docs).toHaveLength(1)
    expect(entries.docs[0]?.deletedAt).toBeUndefined()
  })

  it('sweep with retention 0 never purges', async () => {
    const { fs, engine } = await bench()
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    backdate(fs, 40)
    expect(await engine.sweepTrash(new Date(), 0)).toBe(0)
    expect((await engine.trash()).docs).toHaveLength(1)
  })

  it('restore and purge forget the registry entry', async () => {
    const { fs, engine } = await bench()
    await engine.remove({ path: '10-技术/11-AI/2026-08-14-a.md' })
    const first = await engine.trash()
    const restored = await engine.restore({ path: first.docs[0]!.path })
    expect(Object.keys(registryOf(fs).entries)).toHaveLength(0)
    await engine.remove({ path: restored.to })
    const second = await engine.trash()
    await engine.purge({ path: second.docs[0]!.path })
    expect(Object.keys(registryOf(fs).entries)).toHaveLength(0)
  })
})

describe('KbEngine refresh', () => {
  /** Seed one indexed library with a single document. */
  async function bench(): Promise<{ fs: MemoryFs; engine: KbEngine }> {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/00-inbox/2026-08-10-a.md', doc('甲', '2026-08-10'))
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    return { fs, engine }
  }

  it('absorbs documents added outside the engine', async () => {
    const { fs, engine } = await bench()
    expect((await engine.list({})).map(item => item.path)).toEqual(['00-inbox/2026-08-10-a.md'])
    fs.seed('kb/10-技术/2026-08-15-外部.md', doc('外部新增', '2026-08-15'))
    await engine.refresh()
    const paths = (await engine.list({})).map(item => item.path)
    expect(paths).toContain('10-技术/2026-08-15-外部.md')
    expect((await engine.search('外部新增', 10)).total).toBe(1)
  })

  it('drops documents blanked outside the engine', async () => {
    const { fs, engine } = await bench()
    fs.entries.get('kb/00-inbox/2026-08-10-a.md')!.text = ' '
    await engine.refresh()
    expect((await engine.list({})).map(item => item.path)).toEqual([])
  })

  it('serves refreshed content for externally edited documents', async () => {
    const { fs, engine } = await bench()
    fs.entries.get('kb/00-inbox/2026-08-10-a.md')!.text = doc('甲改', '2026-08-15')
    await engine.refresh()
    const result = await engine.get({ path: '00-inbox/2026-08-10-a.md' })
    expect(result.meta.title).toBe('甲改')
  })

  it('rewrites the on-disk index after a refresh', async () => {
    const { fs, engine } = await bench()
    fs.seed('kb/00-inbox/2026-08-15-外部.md', doc('外部新增', '2026-08-15'))
    await engine.refresh()
    const index = JSON.parse(fs.entries.get('kb/_meta/index.json')!.text) as { docs: Record<string, unknown> }
    expect(index.docs['00-inbox/2026-08-15-外部.md']).toBeDefined()
  })
})

describe('KbEngine search ranking', () => {
  /** Seed one library from path → markdown text and load the engine. */
  async function bench(files: Record<string, string>): Promise<KbEngine> {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    for (const [path, text] of Object.entries(files)) fs.seed('kb/' + path, text)
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    return engine
  }

  it('ranks title matches above body-only matches', async () => {
    const engine = await bench({
      '10-技术/2026-08-10-title.md': '---\ntitle: 检索增强\nupdated: 2026-08-10\n---\n\n正文\n',
      '20-学习笔记/2026-08-12-body.md': '---\ntitle: 笔记\nupdated: 2026-08-12\n---\n\n正文里提到检索相关概念\n',
    })
    const { hits } = await engine.search('检索', 10)
    expect(hits.map(hit => hit.path)).toEqual(['10-技术/2026-08-10-title.md', '20-学习笔记/2026-08-12-body.md'])
  })

  it('returns ranked hits for a partial multi-term query instead of an empty AND result', async () => {
    const engine = await bench({
      '10-技术/2026-08-10-ai.md': '---\ntitle: 人工智能\nupdated: 2026-08-10\n---\n\n正文\n',
      '20-学习笔记/2026-08-12-data.md': '---\ntitle: 数据处理\nupdated: 2026-08-12\n---\n\n正文\n',
    })
    const { hits, total } = await engine.search('人工数据', 10)
    expect(total).toBe(2)
    expect(hits.map(hit => hit.path).sort()).toEqual([
      '10-技术/2026-08-10-ai.md', '20-学习笔记/2026-08-12-data.md',
    ])
  })

  it('tolerates one-character typos through neighbor grams', async () => {
    const engine = await bench({
      '10-技术/2026-08-10-tech.md': '---\ntitle: 技术要点\nupdated: 2026-08-10\n---\n\n正文\n',
    })
    const { hits, total } = await engine.search('技束要点', 10)
    expect(total).toBe(1)
    expect(hits[0]?.path).toBe('10-技术/2026-08-10-tech.md')
  })

  it('ranks alias matches above body-only matches', async () => {
    const engine = await bench({
      '10-技术/2026-08-10-rag.md': '---\ntitle: 检索增强生成\naliases: [RAG]\nupdated: 2026-08-10\n---\n\n正文\n',
      '20-学习笔记/2026-08-12-notes.md': '---\ntitle: 随手记\nupdated: 2026-08-12\n---\n\n正文中 RAG 概念\n',
    })
    const { hits } = await engine.search('RAG', 10)
    expect(hits.map(hit => hit.path)).toEqual(['10-技术/2026-08-10-rag.md', '20-学习笔记/2026-08-12-notes.md'])
  })

  it('applies status, tag, directory, and title filters to ranked hits', async () => {
    const engine = await bench({
      '00-inbox/2026-08-10-inbox.md': '---\ntitle: 收集箱条目\ntags: [测试]\nupdated: 2026-08-10\n---\n\n正文\n',
      '10-技术/2026-08-12-filed.md': '---\ntitle: 技术条目\ntags: [测试]\nupdated: 2026-08-12\n---\n\n正文\n',
      '10-技术/11-AI/2026-08-13-ai.md': '---\ntitle: AI 笔记\ntags: [AI]\nupdated: 2026-08-13\n---\n\n正文\n',
    })
    expect((await engine.search('条目', 10, { status: 'inbox' })).hits.map(hit => hit.path))
      .toEqual(['00-inbox/2026-08-10-inbox.md'])
    expect((await engine.search('条目', 10, { tag: '测试' })).hits.map(hit => hit.path).sort())
      .toEqual(['00-inbox/2026-08-10-inbox.md', '10-技术/2026-08-12-filed.md'])
    expect((await engine.search('正文', 10, { directory: '10-技术/11-AI' })).hits.map(hit => hit.path))
      .toEqual(['10-技术/11-AI/2026-08-13-ai.md'])
    expect((await engine.search('正文', 10, { title: 'AI' })).hits.map(hit => hit.path))
      .toEqual(['10-技术/11-AI/2026-08-13-ai.md'])
    expect((await engine.search('正文', 10, { title: '不存在的标题' })).total).toBe(0)
  })
})

describe('KbEngine links', () => {
  it('reports outlinks and backlinks for one document', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/2026-08-12-a.md', doc('甲', '2026-08-12', '') + '见 [[乙]] 与 [[丙|显示]]')
    fs.seed('kb/10-技术/2026-08-13-b.md', doc('乙', '2026-08-13', '') + '回链 [[甲]]')
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    const view = await engine.links('10-技术/2026-08-12-a.md')
    expect(view.outLinks).toEqual(['乙', '丙'])
    expect(view.backlinks).toEqual(['10-技术/2026-08-13-b.md'])
  })

  it('fails for an unknown document', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const engine = new KbEngine(ctx.fs, 'kb')
    await expect(engine.links('00-inbox/missing.md')).rejects.toThrow(/文档不存在/)
  })
})

describe('KbEngine image registry rebuild', () => {
  it('scans images, rebuilds the object-format registry, and lists orphans', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/2026-08-12-a.md', doc('甲', '2026-08-12', '') + '正文 ![[diagram.png]]')
    fs.seed('kb/10-技术/diagram.png', 'png-bytes')
    fs.seed('kb/10-技术/orphan.png', 'png-bytes')
    fs.seed('kb/_meta/ignored.png', 'png-bytes')
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    const result = await engine.images()
    expect(result.total).toBe(2)
    expect(result.images.sort()).toEqual(['10-技术/diagram.png', '10-技术/orphan.png'])
    expect(result.orphans).toEqual([{ path: '10-技术/orphan.png', name: 'orphan.png' }])
    const registry = JSON.parse(fs.entries.get('kb/_meta/images.json')!.text) as
      { images: Record<string, { name: string; referenced: boolean }> }
    expect(registry.images['10-技术/diagram.png']).toEqual({ name: 'diagram.png', referenced: true })
    expect(registry.images['10-技术/orphan.png']).toEqual({ name: 'orphan.png', referenced: false })
  })

  it('resolves a link to an image through the rebuilt object-format registry', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/10-技术/diagram.png', 'png-bytes')
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    await engine.images()
    const resolved = await engine.resolve({ name: 'diagram.png' })
    expect(resolved).toEqual({ path: '10-技术/diagram.png', kind: 'image' })
  })
})

describe('KbEngine optimistic-lock conflict', () => {
  it('reports a stale expectVersion as a conflict without touching content or index', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/00-inbox/2026-08-10-a.md', doc('甲', '2026-08-10'))
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    const before = await engine.get({ path: '00-inbox/2026-08-10-a.md' })
    // An external write bumps the file version behind the client's back.
    fs.entries.get('kb/00-inbox/2026-08-10-a.md')!.version++
    const result = await engine.save({
      path: '00-inbox/2026-08-10-a.md', content: '外部覆盖',
      ...(before.version === undefined ? {} : { expectVersion: before.version }),
    })
    expect(result.conflict).toBe(true)
    const after = await engine.get({ path: '00-inbox/2026-08-10-a.md' })
    expect(after.content).toBe(before.content)
    expect(after.content).not.toContain('外部覆盖')
  })

  it('writes through when expectVersion matches the current version', async () => {
    const ctx = new Context()
    await ctx.plugin(MemoryFs)
    const fs = ctx.fs as MemoryFs
    fs.seed('kb/00-inbox/2026-08-10-a.md', doc('甲', '2026-08-10'))
    const engine = new KbEngine(fs, 'kb')
    await engine.ensureInit()
    const before = await engine.get({ path: '00-inbox/2026-08-10-a.md' })
    const result = await engine.save({
      path: '00-inbox/2026-08-10-a.md', content: '正常更新',
      ...(before.version === undefined ? {} : { expectVersion: before.version }),
    })
    expect(result.conflict).toBe(false)
    expect((await engine.get({ path: '00-inbox/2026-08-10-a.md' })).content).toContain('正常更新')
  })
})
